# Generated by Django 4.2.2 on 2024-01-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="adjustment",
            fields=[
                ("调剂位次", models.AutoField(primary_key=True, serialize=False)),
                ("姓名", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "adjustment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="admission",
            fields=[
                (
                    "录取位次",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("姓名", models.CharField(blank=True, max_length=255, null=True)),
                ("专业组号", models.IntegerField(blank=True, null=True)),
                ("专业名称", models.CharField(blank=True, max_length=255, null=True)),
                ("学院名称", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "admission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="admitted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("待录取人数", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "admitted",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="major",
            fields=[
                ("专业组号", models.IntegerField()),
                (
                    "专业代号",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("专业名称", models.CharField(max_length=255)),
                ("学院名称", models.CharField(max_length=255)),
                ("招生计划数", models.IntegerField()),
                ("专业备注", models.CharField(blank=True, max_length=255, null=True)),
                ("办学地点", models.CharField(blank=True, max_length=255, null=True)),
                ("外语语种", models.CharField(blank=True, max_length=50, null=True)),
                ("体检受限1", models.CharField(blank=True, max_length=100, null=True)),
                ("体检受限2", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "major",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "考生号",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("姓名", models.CharField(blank=True, max_length=255, null=True)),
                ("专业组号", models.IntegerField(blank=True, null=True)),
                ("投档成绩", models.IntegerField(blank=True, null=True)),
                ("服从调剂", models.CharField(blank=True, max_length=255, null=True)),
                ("专业志愿1", models.CharField(blank=True, max_length=255, null=True)),
                ("专业志愿2", models.CharField(blank=True, max_length=255, null=True)),
                ("专业志愿3", models.CharField(blank=True, max_length=255, null=True)),
                ("专业志愿4", models.CharField(blank=True, max_length=255, null=True)),
                ("专业志愿5", models.CharField(blank=True, max_length=255, null=True)),
                ("专业志愿6", models.CharField(blank=True, max_length=255, null=True)),
                ("体检受限1", models.CharField(blank=True, max_length=255, null=True)),
                ("体检受限2", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "students",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="withdrawal",
            fields=[
                ("退档位次", models.AutoField(primary_key=True, serialize=False)),
                ("姓名", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "withdrawal",
                "managed": False,
            },
        ),
    ]
