# Generated by Django 4.2.2 on 2023-11-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ALLExaminee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CandidateID", models.IntegerField()),
                ("Name", models.CharField(max_length=8)),
                ("Phonenumber", models.CharField(max_length=11)),
                ("Totalscore", models.CharField(max_length=200)),
                ("Ranking", models.IntegerField()),
                ("adjustment", models.CharField(max_length=10)),
                ("Physicalexamination", models.CharField(max_length=10)),
                ("Foreignlanguagerequirements", models.CharField(max_length=10)),
                ("Firstvolunteer", models.CharField(max_length=200)),
                ("Secondvolunteer", models.CharField(max_length=200)),
                ("Thirdvolunteer", models.CharField(max_length=200)),
                ("Fourthvolunteer", models.CharField(max_length=200)),
                ("Fifthvolunteer", models.CharField(max_length=200)),
                ("Sixthvolunteer", models.CharField(max_length=200)),
            ],
        ),
    ]
